apiVersion: v1
kind: Secret
metadata:
  name: orchestra-secrets
type: Opaque
data:
  # These are placeholder values. In production, replace with actual base64-encoded secrets
  # Example: echo -n "your-secret-value" | base64
  api-key: b3JjaGVzdHJhLXNlY3JldC1rZXk=  # orchestra-secret-key
  postgres-dsn: ZGJuYW1lPW9yY2hlc3RyYSB1c2VyPXBvc3RncmVzIHBhc3N3b3JkPXBvc3RncmVzIGhvc3Q9cG9zdGdyZXMtc2VydmljZQ==  # dbname=orchestra user=postgres password=postgres host=postgres-service
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==  # redis://redis-service:6379/0
  qdrant-url: aHR0cDovL3FkcmFudC1zZXJ2aWNlOjYzMzM=  # http://qdrant-service:6333
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleQ==  # your-openai-api-key